---
title: 'Exercises: 02_data_manipulation'
author: "David"
date: "October 8, 2016"
output: html_document
---
# Pipes `%>%`
## 1 
```{r}
# Question
set.seed(123)
log(mean(sqrt(rnorm(100, mean = 10, sd = 1))), base = 10)

# Answer
library(magrittr)
set.seed(123)
100 %>% rnorm(mean = 10, sd = 1) %>% sqrt %>% mean %>% log(base = 10)
```
## 2
```{r}
# Question
# 2.a
mat <- matrix(rnorm(36, mean = 10, sd = 3), ncol = 6)
# 2.b (hint, write a short function)
mat <- (mat - mean(mat)) / sd(mat)

# Answer
# 2.a
mat  <- 36 %>% rnorm(mean = 10, sd = 3) %>% matrix(ncol = 6)

# 2.b
std <- function(x) {
  x_std <- (x - mean(x)) / sd(x)
  return(x_std)
}
mat %<>% std

# Option 2 to 2.b
# -> vignette("magrittr") # Aliases
mat  <- 36 %>% rnorm(mean = 10, sd = 3) %>% matrix(ncol = 6)
# mat %<>% (. - mean(.)) / sd(.) # ERROR: object '.' not found
mat %<>% {(. - mean(.)) / sd(.)}
```

## 3
```{r}
# Question
paste("Hi this is", rep(c("Alice", "Bob"), each = 2), 
      "my name has", nchar(rep(c("Alice", "Bob"), each = 2)), 
      "letters")
# Answer
c("Alice", "Bob") %>% rep(each = 2) %>% 
  paste("Hi this is", ., "my name has", nchar(.), "letters")
```

# `readr`
```{r}
# 1
# Set working directory or use a project!!!
setwd("~/Dropbox/Promotion/Workshops/R Programming WS/02_data_munging/")

# download.file("https://raw.githubusercontent.com/DavZim/RDataAnalytics/master/data/iris.csv", destfile = "iris.csv")

# 2
library(readr)
iris_df <- read_csv("iris.csv")
iris_df
summary(iris_df)
str(iris_df)
```
```{r, eval = F}
# 3
write_csv(iris_df, "iris2.csv")

# write_csv to subfolder
write_csv(iris_df, "subfolder/iris2.csv")

# write_csv to parent-folder
write_csv(iris_df, "../iris2.csv")
```
```{r, eval=F}
# 3
iris_df2 <- read_csv("https://raw.githubusercontent.com/DavZim/RDataAnalytics/master/data/iris.csv")
```


# Tidy Data

```{r, message=FALSE, warning=FALSE}
library(readr)
library(tidyr)
library(dplyr)
library(lubridate)

url <- "https://raw.githubusercontent.com/DavZim/RDataAnalytics/master/data/stock_data.csv"
wide_df <- read_csv(url)
wide_df[1:5, 1:5] # look only at the first 5 rows and columns

long_df <- gather(wide_df, key = date, value = price, -ticker)
long_df

long_df %<>% separate(col = date, into = c("month", "day", "year"), sep = "[[:punct:]]")
long_df

long_df %<>% unite(date, year, month, day, sep = "-")
long_df

long_df %<>% mutate(date = ymd(paste("20", date, sep = "")))
long_df

str(long_df)
```

# `dplyr`
```{r}
library(nycflights13)
# 1. Operator with the most flights
flights %>% 
  group_by(carrier) %>%
  summarise(n_flights = n()) %>%
  arrange(desc(n_flights))

# 2. Origin airport with the most flights (by what magnitude)
flights %>% 
  group_by(origin) %>%
  summarise(n_flights = n()) %>%
  arrange(desc(n_flights)) %>%
  mutate(frac_of_max = n_flights / max(n_flights),
         frac_of_total = n_flights / sum(n_flights))

# 3. Destination with the longest (average) arrival delay
flights %>%
  group_by(dest) %>%
  summarise(avg_arr_delay = mean(arr_delay, na.rm = T)) %>%
  arrange(desc(avg_arr_delay))
# 4. Date with the least (average) arrival delay
library(fasttime) # for faster time, use fastPOSIXct
flights %>%
  mutate(date = fastPOSIXct(paste(year, month, day, sep = "-"))) %>%
  group_by(date) %>%
  summarise(avg_arr_delay = mean(arr_delay, na.rm = T)) %>%
  arrange(avg_arr_delay)
# 5. Own insights
# a) how many flights had delays: less than 0, 5, 10, 30 1 hr, more?
# a small helper function that returns a category for a given delay
category_fun <- function(delay) {
  ifelse(delay < 0, "<0",
         ifelse(delay < 5, "0<=x<5",
                ifelse(delay < 10, "5<=x<10",
                       ifelse(delay < 30, "10<=x<30",
                              ifelse(delay < 60, "30<=x<60",
                                     "x>60")))))
}

flights %>%
  mutate(delay_category = category_fun(arr_delay)) %>%
  group_by(delay_category) %>%
  summarise(n_delays = n(),
            avg_delay = mean(arr_delay, na.rm = T)) %>%
  arrange(avg_delay) 
```

# Joins
```{r}
# Takes in the coordinates (lat or long) and formats it to a single digit
formatter <- function(deg, min, sec, north_or_east = T) {
  ret <- deg + min / 60 + sec / 60 ^ 2
  if (north_or_east) {
    return(ret)
  } else {
    return(-ret)
  }
}

# BQN: 18°29'42"N 067°07'46W, tz = "AST" = -4
bqn <- data_frame(faa = "BQN", name = "Rafael Hernandez Airport",
                  lat = formatter(18, 29, 42, T),
                  lon = formatter(67, 07, 46, F),
                  alt = NA,
                  tz = -4)

# SJU: 18°26'21"N 066°00'07W, tz = "AST" = -4
sju <- data_frame(faa = "SJU", name = "Luis Munoz Marin International Airport",
                  lat = formatter(18, 26, 21, T),
                  lon = formatter(66, 00, 07, F),
                  alt = NA,
                  tz = -4)

# STT: 18°20'14"N 064°58'24W, tz = "AST" = -4
stt <- data_frame(faa = "STT", name = "Cyril E. King Airport",
                  lat = formatter(18, 20, 14, T),
                  lon = formatter(64, 58, 24, F),
                  alt = NA,
                  tz = -4)

# PSE: 18°00'30"N 066°33'47W, tz = "AST" = -4
pse <- data_frame(faa = "PSE", name = "Mercedita Airport",
                  lat = formatter(18, 00, 30, T),
                  lon = formatter(66, 33, 47, F),
                  alt = NA,
                  tz = -4)

missing_airports <- bind_rows(bqn, sju, stt, pse)
missing_airports
```
## combine the airports
```{r}
# merge the missing airports into airports
airports2 <- bind_rows(airports, missing_airports)
# merge the locations again

df <- flights %>% select(origin, dest, carrier) %>% distinct()

# prepare merge
# 1 rename airports2-variables
airports2_1 <- airports2 %>% select(faa, dest_lat = lat, dest_lon = lon)

df <- left_join(df, airports2_1, by = c("dest" = "faa"))
df

airports2_2 <- airports2 %>% select(faa, origin_lat = lat, origin_lon = lon)

df <- left_join(df, airports2_2, by = c("origin" = "faa"))
df

summary(df)
df %>% filter(is.na(dest_lon)) 
```

## Weather-join
```{r}
df_flight <- flights %>% select(origin, year, month, day, dep_time, dep_delay, hour)

df_weather <- weather %>% select(origin, year, month, day, hour, temp, wind_speed, precip)
df_merged <- left_join(df_flight, df_weather, by = c("origin", "year", "month", "day", "hour"))
df_merged
```


